name: Linux Container Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: vishwasnarayanazure.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME_ACR }}
        password: ${{ secrets.DOCKER_PASSWORD_ACR }}

    - run: |
        docker build . -t ${{ secrets.DOCKER_REGISTRY_URL_ACR }}/myapp:${{ github.sha }}
        docker push v${{ secrets.DOCKER_REGISTRY_URL_ACR }}/myapp:${{ github.sha }}
