name: Trigger auto deployment for vishwasnarayandemo123

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vishwasnarayandemo123-AutoDeployTrigger-dbd0991e-5490-4395-859f-46265315022c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: vishwasnarayan.azurecr.io
          username: ${{ secrets.VISHWASNARAYANDEMO123_REGISTRY_USERNAME }}
          password: ${{ secrets.VISHWASNARAYANDEMO123_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vishwasnarayan.azurecr.io/vishwasnarayandemo123:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.VISHWASNARAYANDEMO123_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n vishwasnarayandemo123 -g DefaultResourceGroup-CCAN --server vishwasnarayan.azurecr.io --username  ${{ secrets.VISHWASNARAYANDEMO123_REGISTRY_USERNAME }} --password ${{ secrets.VISHWASNARAYANDEMO123_REGISTRY_PASSWORD }}
            az containerapp update -n vishwasnarayandemo123 -g DefaultResourceGroup-CCAN --image vishwasnarayan.azurecr.io/vishwasnarayandemo123:${{ github.sha }}
